services:
  postgres:
    container_name: postgres-sql-jsm
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ekassiba@1235$
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: smart_farm
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - joelin-farm
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-jsm
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  joelin-farm:
    driver: bridge
volumes:
  postgres:
    driver: local